export const EXPENSE_CATEGORY_TREE = {
  Salary: ["Salary"],
  Rent: [
    "Rent-Backend Basement",
    "Rent-Backend upper ground floor",
    "Rent-Backend ground floor",
    "Rent-Backend 1st Floor",
    "Rent-Backend Parking",
    "Rent-Backend 4th floor / Top floor",
    "Rent-CD Clinic",
    "Rent-GD clinic",
    "Rent-Manu Vaishali Clinic",
    "Rent-Mansi Vaishali clinic",
    "Rent-Hyderebad Clinic",
    "Rent-Noida Clinic",
    "Rent-Staff Flat",
    "Rent-Deepak staff flat",
    "Rent-P House Rent",
  ],
  Marketing: [
    "Meta ads",
    "Google ads",
    "Ai Sensy",
    "CX Wizard",
    "Marketing Tools",
    "Marketing-Others",
  ],
  "Medical Consumables": [
    "Medical Consumables-OT",
    "Medical Consumables-Others",
  ],
  "Medicine Procurement": ["Medicine Procurement"],
  "Professional Expenses": [
    "Turkey Technician",
    "On Call Staff",
    "Legal Consultant Fee",
    "Finance Consultant Fee",
    "Freelancer Fee",
  ],
  "Electricity Bill": [
    "Electricity Exp-Backend basement",
    "Electricity Exp-Backend upper ground floor",
    "Electricity Exp-Backend ground floor",
    "Electricity Exp-Backend 1st Floor",
    "Electricity Exp-Backend 4th floor / Top floor",
    "Electricity Exp-CD Clinic",
    "Electricity Exp-GD clinic",
    "Electricity Exp-Manu Vaishali Clinic",
    "Electricity Exp-Mansi Vaishali clinic",
    "Electricity Exp-Hyderebad Clinic",
    "Electricity Exp-Noida Clinic",
    "Electricity Exp-Staff Flat",
    "Electricity Exp-Deepak staff flat",
    "Electricity Exp-P house",
  ],
  Incentive: [
    "Sales Incentive-Agents",
    "Sales Incentive--Counsellor",
    "Sales Incentive- Technician",
    "Sales Incentive-- Medicine",
    "Sales Incentive-- HR",
    "Incentive-- Finance",
    "Incentive- Marketing Team",
    "Incentive - Others",
  ],
  Commision: [
    "Patient Commission Paid to Patients",
    "Patient Commission Paid to Muskan",
    "HR Commission",
    "Commission-others",
  ],
  "Welfare Expenses": [
    "Staff Meals-Management",
    "Staff Welfare",
    "Pantry Expenses",
    "Office Party Expenses",
  ],
  "Office Exp.": [
    "Office Consumables",
    "office Repairs and Maintainence",
    "Vehicle Maintainance",
    "Printing & stationery",
    "Conveyance/Freight",
  ],
  "Lab Expenses": ["Lab Expenses", "Lab Consumables"],
  "Patient Related Expenses": [
    "Patient Meals",
    "Patient Refunds",
    "PATIENT EMI",
    "PATIENT TREATMENT CHARGES",
  ],
  "Interest Expenses": ["Interest Expenses"],
  Taxes: [
    "GST",
    "ROC",
    "TDS",
    "Income Tax",
    "GST Ryan Skin",
    "ROC Ryan Medihub",
    "TDS on Rent Ryan Medihub",
    "TDS on Rent Ryan Skin",
    "TDS on Professional Service Ryan Medihub",
    "TDS on Professional Service Ryan Skin",
    "TDS on Salary Service Ryan Medihub",
    "TDS on Salary Service Ryan Skin",
    "TDS on Contractor Ryan Medihub",
    "TDS on Contractor Ryan Skin",
    "TDS on Commission Ryan Medihub",
    "TDS on Commission Ryan Skin",
    "TDS on others Ryan Medihub",
    "TDS on others Ryan Skin",
    "Income Tax Ryan Medihub",
    "Income Tax Ryan Skin",
  ],
  Loans: ["LA DOLCE", "Loan Repayment", "Loan Others"],
  "Software Rental Expenses": ["Software Rental Expenses"],
  "Hardware Rental Expenses": [
    "AC Rent",
    "Laptop/System Rent",
    "Printer Rental Expenses",
    "Rental Others",
  ],
  "Travelling Expenses": ["Travelling Expenses"],
  "Hotel Charges": ["Hotel Charges"],
  "Telephone Expenses": [
    "Staff Recharge",
    "Mobile Repairing",
    "Interenet Recharge/Wifi",
  ],
  "Bank Charges": ["Bank Charges", "External Charges"],
  "Forex Conversion and Fluctuation Charges": [
    "Forex Conversion and Fluctuation Charges",
  ],
  "Asset Based Payment": [
    "Hardware-Laptop/Computer/Mobile etc",
    "Security & Deposits",
  ],
  Drawings: [
    "Personal Payments",
    "Handover to Family",
    "Handover to Backend",
    "Loan Repayment",
  ],
  "Collab Clinic Payment": ["Collab Clinic Payment"],
  "Medical testing kit": ["Medical testing kit"],
  Miscellaneous: ["Miscellaneous"],
  Borrowings: ["Deposit Received", "Loan from Party", "Advance Received"],
};

export const EXPENSE_CATEGORIES = Object.keys(EXPENSE_CATEGORY_TREE);

export const getExpenseTypes = (category) =>
  EXPENSE_CATEGORY_TREE[category] || [];

export const PAYABLE_EXPENSE_CATEGORIES = [
  "Salary",
  "Rent",
  "Medical Consumables",
  "Medicine Procurement",
  "Professional Expenses",
  "Electricity Bill",
  "Incentive",
  "Commision",
  "Lab Expenses",
  "Interest Expenses",
  "Taxes",
  "Loans",
  "Software Rental Expenses",
  "Hardware Rental Expenses",
];

const PAYABLE_CATEGORIES_OWNED_ELSEWHERE = ["Salary", "Incentive", "Commision"];

export const PAYABLE_EXPENSE_DROPDOWN_CATEGORIES =
  PAYABLE_EXPENSE_CATEGORIES.filter(
    (cat) => !PAYABLE_CATEGORIES_OWNED_ELSEWHERE.includes(cat),
  );

export const DIRECT_PAYMENT_CATEGORIES = [
  "Marketing",
  "Welfare Expenses",
  "Office Exp.",
  "Travelling Expenses",
  "Hotel Charges",
  "Telephone Expenses",
  "Bank Charges",
  "Forex Conversion and Fluctuation Charges",
  "Asset Based Payment",
  "Drawings",
  "Miscellaneous",
  "Medical testing kit",
  "Patient Related Expenses",
];

export const TDS_TAX_TYPES = [
  "GST Ryan Skin",
  "ROC Ryan Medihub",
  "TDS on Rent Ryan Medihub",
  "TDS on Rent Ryan Skin",
  "TDS on Professional Service Ryan Medihub",
  "TDS on Professional Service Ryan Skin",
  "TDS on Salary Service Ryan Medihub",
  "TDS on Salary Service Ryan Skin",
  "TDS on Contractor Ryan Medihub",
  "TDS on Contractor Ryan Skin",
  "TDS on Commission Ryan Medihub",
  "TDS on Commission Ryan Skin",
  "TDS on others Ryan Medihub",
  "TDS on others Ryan Skin",
  "Income Tax Ryan Medihub",
  "Income Tax Ryan Skin",
];
